spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8000/eplscheduler2021-22
    username: jimin
    password: simon1126
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    check-template-location: true
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: update
      show-sql: 'true'
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        show-sql: true
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
